version: '3.8'

services:
  bot:
    build: .
    container_name: tg_dark_pdf_bot
    volumes:
      - ./tmp:/app/tmp
      - ./config.yaml:/app/config.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
